---
###############################################################################
#                           Authelia Configuration                            #
###############################################################################

theme: dark #light/dark
jwt_secret: your_jwt_secret #any text or number you want to add here to create jwt Token

default_redirection_url: https://example.com/ #where to redirect for a non-existent URL

server:
  host: 0.0.0.0
  port: 9091
  path: ""
  buffers:
    read: 65536
    write: 65536
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: "" #the path
    certificate: "" #the path

log:
  level: debug

totp:
  issuer: example.com #your authelia top-level domain
  period: 30
  skew: 1

authentication_backend:
  #disable_reset_password: false
  refresh_interval: 5m
  file:
    path: /config/users_database.yml #this is where your authorized users are stored
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

password_policy:
  standard:
    enabled: false
    min_length: 8
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: true
  zxcvbn:
    enabled: true
    min_score: 3

access_control:
  default_policy: one_factor
  rules:
    ## bypass rule
    - domain:
        - "auth.example.com" #This should be your authentication URL
      policy: bypass
    - domain: "example.com" #example domain to protect
      policy: one_factor
    #- domain: "example.com" #example subdomain to protect
    #  policy: one_factor
    #- domain: "example.com" #example subdomain to protect
    #  policy: one_factor
    #- domain: "example.com" #example subdomain to protect
      #policy: one_factor
    #- domain: "*.example.com" #example to protect all subdomains under top-level domain
      #policy: one_factor
      #add or remove additional subdomains as necessary. currenlty only supports ONE top-level domain
      #any time you add a new subdomain, you will need to restart the Authelia container to recognize the new settings/rules

session:
  name: authelia_session
  secret: unsecure_session_secret #any text or number you want to add here to create jwt Token
  expiration: 3600  # 1 hour
  inactivity: 3600  # 1 hour
  domain: example.com  # Should match whatever your root protected domain is

regulation:
  max_retries: 5
  find_time: 10m
  ban_time: 24h

storage:
  local:
    path: /config/db.sqlite3 #this is your databse. You could use a mysql database if you wanted, but we're going to use this one.
  encryption_key: insert_here_your_encryption_key  #added Dec 5 2021

notifier:
  disable_startup_check: true #true/false
  #this is a configuration for gmail but you can also use your own email domain this is useful if you want to use email for password  recovery en 2fa setup
  #remember to open firewall port to google smtp ip
  smtp:
   username: your_email@gmail.com #your email address
   password: your_password_token #your password you need to enable the 2fa on your email and then create a token access in the section "app password" of your google account page
   host: smtp.gmail.com #email smtp server
   port: 587 #email smtp port
   sender: your_email@gmail.com
   identifier: localhost
   subject: "[Authelia] {title}" #email subject
   startup_check_address: your_email@gmail.com
   disable_require_tls: false
   disable_html_emails: false
   tls:
     skip_verify: false
     minimum_version: TLS1.2
  # # if you don't have or don't want to setup an email for notifier you can use the filesystem option, all the the email that configuration link are stored in this file ( but just once )
  # filesystem:
  #   filename: /config/notification.txt
...
